export { Header } from './Header'
export { Hello } from './Hello'
export { Devices } from './Devices'
export { About } from './About'
export { Recent } from './Recent'
export { Footer } from './Footer'
